### ISSUE TITLE
Clean SHADOW font

### ISSUE THREAD

**Issue by mrender** [IMFUZZ/vscode_banner_comments#2]
What abou making the SHADOW font with the "blocky" style, but without it´s backdrop?
Like this:

//   ██████  
// ██             
// ██       ███  
// ██          ██
//    ██████

Not this:
//    ██████╗  
// ██╔════╝
// ██║     ███╗
// ██║        ██║
// ╚██████╔╝
//   ╚═════╝

**Comment by mrender** [comment]
mmmm... nevermind.... 
It seems it´s not on you to change it. Sorry for that! ;)

**Comment by daniel-junior-dube** [comment]
Sorry for responding so late.

The fonts are indeed provided by the figlet module.

Thanks!
